---
title: "Music & Mental Health - Exploratory Data Analysis"
author: "Jan Moskal"
date: "2025-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggcorrplot)
library(e1071)
```


### Wczytywanie danych
```{r}
data <- readRDS("df_EDA.rds")
df <- readRDS("df.rds")
```

### Podstawowe statystyki opisowe dla zmiennych numerycznych
```{r}
df %>%
  select(where(is.numeric)) %>%
  summary()
```

Z ciekawych rzeczy widać tutaj, że w dwóch kolumnach numerycznych występują braki danych tzn. `Age` i `BPM`

### Wykres macierzy korelacji dla zmiennych numerycznych
```{r}
df %>%
  select(where(is.numeric)) %>%
  cor(use = "complete.obs") %>%
  round(2) %>% 
  ggcorrplot(lab = TRUE)
```

### Zestawienie liczby braków danych
```{r}
df %>%
  summarise_all(~sum(is.na(.))) %>%
  pivot_longer(everything(), names_to = "Zmienna", values_to = "Liczba braków") %>%
  filter(`Liczba braków` > 0) %>% 
  arrange(desc(`Liczba braków`))
```

